feat: Add `http` scheme support for the REST API
terraform-routeros/terraform-provider-routeros pull request #398
Opened 2024-03-26 21:31 UTC by dokmic

This PR enables the `http` scheme support in the connection settings.

2024-03-27 05:18 UTC, vaerh commented
Hi Michael!

Originally this functionality was in the provider but on early versions of ROS it didn't work for some reason.

Please look at the differences between your PR and my implementation. It seems to me that `useTLS = false` is still needed.

https://github.com/vaerh/terraform-provider-routeros/commit/a7869fbc5bdfc95c725ecc1b66763969b2c9716c

2024-03-27 16:59 UTC, vaerh requested changes
Please see the comment on the PR

2024-03-28 21:44 UTC, dokmic commented
@vaerh I've been exploiting this feature locally for a few weeks already, and so far so good. It works perfectly with a few ROS instances.

The `useTLS = false` statement is unnecessary, as it only matters when the selected transport is `TransportAPI`.

2024-03-29 02:20 UTC, merged

2024-03-29 02:22 UTC, vaerh commented
:tada: This PR is included in version 1.42.0 :tada:

The release is available on [GitHub release](https://github.com/terraform-routeros/terraform-provider-routeros/releases/tag/v1.42.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: