Fix interface list member missing `comment`
terraform-routeros/terraform-provider-routeros pull request #468
Opened 2024-05-27 13:12 UTC by OJFord

2024-05-27 19:42 UTC, vaerh requested changes
I don't mind, but please replace with `KeyComment: PropCommentRw,`.
You can keep the documentation intact, it is generated at each release and in the HC registry it is published with it.

2024-05-28 00:04 UTC, OJFord commented
Ah 👍🏻 thanks

2024-05-28 06:38 UTC, merged

2024-05-28 06:40 UTC, vaerh commented
:tada: This PR is included in version 1.52.0 :tada:

The release is available on [GitHub release](https://github.com/terraform-routeros/terraform-provider-routeros/releases/tag/v1.52.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2024-05-28 06:52 UTC, vaerh commented
:tada: This PR is included in version 1.52.0 :tada:

The release is available on [GitHub release](https://github.com/terraform-routeros/terraform-provider-routeros/releases/tag/v1.52.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: